//
//  NavigationControllerInterfaces.swift
//  Superheroes
//
//  Created by Adam Cseke on 2022. 03. 02..
//  Copyright (c) 2022. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol NavigationControllerWireframeInterface: WireframeInterface {
}

protocol NavigationControllerViewInterface: ViewInterface {
}

protocol NavigationControllerPresenterInterface: PresenterInterface {
}

protocol NavigationControllerInteractorInterface: InteractorInterface {
}
