//
//  NavigationViewController.swift
//  Superheroes
//
//  Created by Adam Cseke on 2022. 03. 02..
//  Copyright (c) 2022. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class NavigationViewController: UINavigationController {

    // MARK: - Public properties -

    var presenter: NavigationControllerPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        setup()
    }
    
    private func setup() {
        setupNavigationController()
    }
    private func setupNavigationController() {
        navigationBar.isOpaque = false
        navigationBar.backgroundColor = .clear
        navigationBar.prefersLargeTitles = true
        let attributes = [NSAttributedString.Key.foregroundColor: Colors.orange.color]
        self.navigationBar.largeTitleTextAttributes = attributes
    }

}

// MARK: - Extensions -

extension NavigationViewController: NavigationControllerViewInterface {
}
