//
//  NavigationControllerPresenter.swift
//  Superheroes
//
//  Created by Adam Cseke on 2022. 03. 02..
//  Copyright (c) 2022. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class NavigationControllerPresenter {

    // MARK: - Private properties -

    private unowned let view: NavigationControllerViewInterface
    private let interactor: NavigationControllerInteractorInterface
    private let wireframe: NavigationControllerWireframeInterface

    // MARK: - Lifecycle -

    init(
        view: NavigationControllerViewInterface,
        interactor: NavigationControllerInteractorInterface,
        wireframe: NavigationControllerWireframeInterface
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension NavigationControllerPresenter: NavigationControllerPresenterInterface {
}
