//
//  FightInterfaces.swift
//  Superheroes
//
//  Created by Adam Cseke on 2022. 03. 14..
//  Copyright (c) 2022. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol FightWireframeInterface: WireframeInterface {
}

protocol FightViewInterface: ViewInterface {
}

protocol FightPresenterInterface: PresenterInterface {
}

protocol FightInteractorInterface: InteractorInterface {
}
