//
//  FightPresenter.swift
//  Superheroes
//
//  Created by Adam Cseke on 2022. 03. 14..
//  Copyright (c) 2022. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class FightPresenter {

    // MARK: - Private properties -

    private unowned let view: FightViewInterface
    private let interactor: FightInteractorInterface
    private let wireframe: FightWireframeInterface

    // MARK: - Lifecycle -

    init(
        view: FightViewInterface,
        interactor: FightInteractorInterface,
        wireframe: FightWireframeInterface
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension FightPresenter: FightPresenterInterface {
}
