//
//  FightInteractor.swift
//  Superheroes
//
//  Created by Adam Cseke on 2022. 03. 14..
//  Copyright (c) 2022. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class FightInteractor {
    let dataProvider: SuperheroesDatabaseManager = DatabaseManager.main
}

// MARK: - Extensions -

extension FightInteractor: FightInteractorInterface {
    func isInTheFavorites(entity: Heroes) -> Bool {
            if DatabaseManager.main.getHeroes().first(where: { $0.id == entity.id }) != nil {
                return true
            } else {
                return false
            }
        }
}
