//
//  FightViewController.swift
//  Superheroes
//
//  Created by Adam Cseke on 2022. 03. 14..
//  Copyright (c) 2022. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import SwiftUI
import UIKit

@available(iOS 13.0.0, *)
struct Fight_Preview: PreviewProvider {
    static var previews: some View {
        Group {
            ViewControllerPreview {
                FightWireframe().viewController
            }
        }
    }
}

final class FightViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: FightPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
    }

}

// MARK: - Extensions -

extension FightViewController: FightViewInterface {
}
