//
//  FavoritesInterfaces.swift
//  Superheroes
//
//  Created by Adam Cseke on 2022. 03. 02..
//  Copyright (c) 2022. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol FavoritesWireframeInterface: WireframeInterface {
    func pushToDetails(hero: Heroes)
}

protocol FavoritesViewInterface: ViewInterface {
    func reloadCollectionView()
}

protocol FavoritesPresenterInterface: PresenterInterface {
    func numberOfSections() -> Int
    func numberOfItem(in section: Int) -> Int
    func cellForItem(at indexPath: IndexPath) -> Heroes
    func getFavorites()
    func favoritesButtonTapped(indexPath: IndexPath)
    func pushToDetails(hero: Heroes)
    func searchButtonTapped(name: String)
}

protocol FavoritesInteractorInterface: InteractorInterface {
    func isInTheFavorites(entity: Heroes) -> Bool
    func delete(entity: Heroes, completion: BoolCompletition?)
    func insert(entity: Heroes, completion: BoolCompletition?)
}
