//
//  FavoritesInterfaces.swift
//  Superheroes
//
//  Created by Adam Cseke on 2022. 03. 02..
//  Copyright (c) 2022. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol FavoritesWireframeInterface: WireframeInterface {
}

protocol FavoritesViewInterface: ViewInterface {
//    func pushfavorites(favorites: [Heroes])
}

protocol FavoritesPresenterInterface: PresenterInterface {
//    func getFavorites()
}

protocol FavoritesInteractorInterface: InteractorInterface {
}
