//
//  FavoritesWireframe.swift
//  Superheroes
//
//  Created by Adam Cseke on 2022. 03. 02..
//  Copyright (c) 2022. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class FavoritesWireframe: BaseWireframe {

    // MARK: - Module setup -

    init() {
        let moduleViewController = FavoritesViewController()
        super.init(viewController: moduleViewController)
        
        let interactor = FavoritesInteractor()
        let presenter = FavoritesPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension FavoritesWireframe: FavoritesWireframeInterface {
}
