//
//  SearchInterfaces.swift
//  Superheroes
//
//  Created by Adam Cseke on 2022. 03. 02..
//  Copyright (c) 2022. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol SearchWireframeInterface: WireframeInterface {
    func pushToDetails(hero: Heroes)
}

protocol SearchViewInterface: ViewInterface {
    func reloadCollectionView()
}

protocol SearchPresenterInterface: PresenterInterface {
    func getSuperHeroes() -> [Heroes]
    func searchButtonTapped(name: String)
    func didTapOnCell(hero: Heroes)
    func pushToDetails(hero: Heroes)
}

protocol SearchInteractorInterface: InteractorInterface {
    func getSuperheroes(name: String, completion: @escaping SuperheroesLoaded )
}
