//
//  SearchWireframe.swift
//  Superheroes
//
//  Created by Adam Cseke on 2022. 03. 02..
//  Copyright (c) 2022. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class SearchWireframe: BaseWireframe, AlertViewDelegate {
    func buttonOneTapped() {
    }
    
    func buttonTwoTapped() {
    }
    
    // MARK: - Module setup -

    init() {
        let moduleViewController = SearchViewController()
        super.init(viewController: moduleViewController)
        
        let interactor = SearchInteractor()
        let presenter = SearchPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension SearchWireframe: SearchWireframeInterface {
    func pushToDetails(hero: Heroes) {
        let detailWF = DetailWireframe(hero: hero)
        navigationController?.pushWireframe(detailWF)
    }
    
    func presentAlert(title: String, description: String, buttonText: String, alertImage: UIImage, buttonTwoLabel: String, buttonIsHidden: Bool) {
        let alertVC = AlertViewController(title: title, message: description, buttonLabel: buttonText, alertImage: alertImage, buttonLabelTwo: buttonTwoLabel, buttonHidden: buttonIsHidden)
        alertVC.modalTransitionStyle = .crossDissolve
        alertVC.modalPresentationStyle = .overFullScreen
        alertVC.alertDelegate = self
        navigationController?.present(alertVC, animated: true)
    }
}
