//
//  SearchInteractor.swift
//  Superheroes
//
//  Created by Adam Cseke on 2022. 03. 02..
//  Copyright (c) 2022. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class SearchInteractor {
    let provider: SuperheroesService = RestClient.shared
}

// MARK: - Extensions -

extension SearchInteractor: SearchInteractorInterface {
    func getSuperheroes(name: String, completion: @escaping SuperheroesLoaded) {
        provider.getSuperheroes(name: name, completion: completion)
    }
    
}
