//
//  SearchViewController.swift
//  Superheroes
//
//  Created by Adam Cseke on 2022. 03. 02..
//  Copyright (c) 2022. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import SwiftUI
import UIKit

@available(iOS 13.0.0, *)
struct Search_Preview: PreviewProvider {
    static var previews: some View {
        Group {
            ViewControllerPreview {
                SearchWireframe().viewController
            }
            ViewControllerPreview {
                SearchWireframe().viewController
            }
            .preferredColorScheme(.dark)
            
        }
    }
}

final class SearchViewController: UIViewController {

    var searchVC = UISearchController(searchResultsController: nil)
    
    // MARK: - Public properties -

    var presenter: SearchPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        setup()
    }
    
    private func setup() {
        configureViewController()
        configureSearchController()
    }
    
    private func configureViewController() {
        view.backgroundColor = .systemBackground
    }
    
    private func configureSearchController() {
        searchVC.hidesNavigationBarDuringPresentation = true
        searchVC.searchBar.sizeToFit()
        searchVC.searchBar.placeholder = L10n.SearchViewController.SearchBar.placeholder
        searchVC.automaticallyShowsCancelButton = true
        searchVC.obscuresBackgroundDuringPresentation = true
        searchVC.searchBar.tintColor = Colors.orange.color
        searchVC.searchBar.delegate = self
        navigationItem.searchController = searchVC
    }
}

// MARK: - Extensions -

extension SearchViewController: SearchViewInterface {
}

extension SearchViewController: UISearchBarDelegate {
    
    func searchBarSearchButtonClicked(_ searchBar: UISearchBar) {
        guard let text = searchBar.text, !text.isEmpty else {
            return
        }
        searchVC.dismiss(animated: true, completion: nil)
    }
}
