//
//  SearchPresenter.swift
//  Superheroes
//
//  Created by Adam Cseke on 2022. 03. 02..
//  Copyright (c) 2022. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class SearchPresenter {
    
    // MARK: - Private properties -
    
    private unowned let view: SearchViewInterface
    private let interactor: SearchInteractorInterface
    private let wireframe: SearchWireframeInterface
    
    private var selectedHeroName: String = ""
    private var selectedHeroImage: String = ""
    private var heroes: [Heroes] = []
    private var text: String = ""
    private var isFavorite: Bool = false
    private var favorites: [Heroes] = []
    private var saveButtonImage: NSAttributedString?
    
    // MARK: - Lifecycle -
    
    init(
        view: SearchViewInterface,
        interactor: SearchInteractorInterface,
        wireframe: SearchWireframeInterface
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
    
    func viewDidLoad() {
        view.setSaveButton(buttonImage: saveButtonImage ?? NSAttributedString())
    }
}

// MARK: - Extensions -

extension SearchPresenter: SearchPresenterInterface {
    
//    func favoritesButtonTapped(indexPath: IndexPath) {
//        isFavorite = interactor.isInTheFavorites(name: selectedHeroName)
//        heroes[indexPath.row].isFavorite.toggle()
//        heroes.forEach { hero in
//            if hero.isFavorite == true && !favorites.contains(where: { $0 == hero }) {
//                favorites.append(hero)
//            } else if hero.isFavorite == false {
//                favorites.removeAll(where: { $0 == hero })
//            }
//        }
//        
//        if self.isFavorite {
//            interactor.delete(name: selectedHeroName) { _ in
//                self.isFavorite = false
//            }
//        } else {
//            interactor.insert(name: selectedHeroName, image: selectedHeroImage) { _ in
//                self.isFavorite = true
//            }
//        }
//        
//    }
    
    func numberOfSections() -> Int {
        1
    }
    
    func numberOfItem(in section: Int) -> Int {
        heroes.count
    }
    
    func cellForRow(at indexPath: IndexPath) -> Heroes {
        selectedHeroImage = heroes[indexPath.row].image.url
        selectedHeroName = heroes[indexPath.row].name
        return heroes[indexPath.row]
    }
    
    func searchVCDismissed() {
        heroes.removeAll()
        self.view.reloadCollectionView()
    }
    
    func pushToDetails(hero: Heroes) {
        wireframe.pushToDetails(hero: hero)
    }
    
    func didTapOnCell(hero: Heroes) {
        pushToDetails(hero: hero)
    }
    
    func searchButtonTapped(name: String) {
        text = name
        if text.isEmpty {
            return
        }
        search(name: text)
    }
    
    private func search(name: String) {
        interactor.getSuperheroes(name: name) { result in
            switch result {
                
            case .success(let heroes):
                
                self.heroes = heroes.results
                self.view.reloadCollectionView()
                
            case .failure(let error):
                print(error.localizedDescription)
            }
        }
    }
    
}
