//
//  DetailPresenter.swift
//  Superheroes
//
//  Created by Adam Cseke on 2022. 03. 03..
//  Copyright (c) 2022. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import UIKit

final class DetailPresenter {
    
    // MARK: - Private properties -
    
    private unowned let view: DetailViewInterface
    private let interactor: DetailInteractorInterface
    private let wireframe: DetailWireframeInterface
    
    private var hero: Heroes
    private var isFavorite: Bool = false
    private var favorites: [Heroes] = []
    private var navBarImage: String = ""
    private var comments: [String] = []
    private var textOfTextview: String = ""
    private var cutText: String?
    
    // MARK: - Lifecycle -
    
    init(
        view: DetailViewInterface,
        interactor: DetailInteractorInterface,
        wireframe: DetailWireframeInterface,
        hero: Heroes
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
        self.hero = hero
    }
    
    func viewDidLoad() {
        view.pushHeroName(hero: hero)
    }
    
    func viewWillAppear(animated: Bool) {
        view.pushComments(comments: comments)
    }
}

// MARK: - Extensions -
extension DetailPresenter: DetailPresenterInterface {
    func buttonCancelTapped(range: NSRange, text: String, clipBoardText: String) {
        textOfTextview = text.replacingOccurrences(of: clipBoardText, with: "")
        self.view.pushCutText(text: textOfTextview)
    }
    
    func buttonCutTapped(range: NSRange, text: String) {
        let newText = (textOfTextview as NSString).replacingCharacters(in: range, with: text)
        if newText.count > 500 {
            textOfTextview = String(newText.prefix(500))
        }
        self.view.pushCutText(text: textOfTextview)
    }
    
    func checkIfLongText(text: String, delegate: AlertViewDelegate?) {
        if text.count > 501 {
            textOfTextview = text
            wireframe.presentAlert(title: L10n.DetailViewController.Comments.Alert.title,
                                   description: L10n.DetailViewController.Comments.Alert.description,
                                   buttonText: L10n.DetailViewController.Comments.Alert.Button.One.title,
                                   alertImage: UIImage(systemName: "scissors") ?? UIImage(),
                                   buttonTwoLabel: L10n.DetailViewController.Comments.Alert.Button.Two.title,
                                   buttonTwoIsHidden: false,
                                   delegate: delegate)
        }
        
    }
    
    func binButtonTapped() {
        interactor.deleteComment(entity: self.hero) { _ in
            self.view.pushComments(comments: self.comments)
            print("Delete done...")
        }
    }
    
    func getComments() {
        comments = DatabaseManager.main.getComments(entity: self.hero)
    }
    
    func commentPushButtonTapped(comment: String, date: Date ) {
        interactor.insertComment(entity: self.hero, comment: comment, date: date) { _ in
            print("Done...")
        }
    }
    
    func favoritesButtonTapped() {
        hero.isFavorite.toggle()
        isFavorite = interactor.isInTheFavorites(entity: hero)
        var newFavorites: [Heroes] = []
        favorites.forEach { hero in
            if hero.isFavorite == true {
                newFavorites.append(hero)
            }
        }
        if self.isFavorite {
            interactor.delete(entity: hero) { _ in
                self.isFavorite = false
            }
        } else {
            interactor.insert(entity: hero) { _ in
                self.isFavorite = true
            }
        }
        self.getFavorites()
    }
    
    func getFavorites() {
        favorites = DatabaseManager.main.getHeroes()
        if favorites.first(where: {$0.id == hero.id}) != nil {
            hero.isFavorite = true
            navBarImage = "star.fill"
        } else {
            hero.isFavorite = false
            navBarImage = "star"
        }
        self.view.setNavBarImage(image: navBarImage)
    }
    
    func powerstatsButtonTapped() {
        view.setPowerstatsButton(selected: true)
    }
    
    func characteristicsButtonTapped() {
        view.setCharacteristicsButton(selected: true)
    }
    
    func commentsButtonTapped() {
        view.setCommentsButton(selected: true)
    }
    
}
