//
//  DetailInterfaces.swift
//  Superheroes
//
//  Created by Adam Cseke on 2022. 03. 03..
//  Copyright (c) 2022. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol DetailWireframeInterface: WireframeInterface {
}

protocol DetailViewInterface: ViewInterface {
    func pushHeroName(hero: Heroes)
    func setPowerstatsButton(selected: Bool)
    func setCharacteristicsButton(selected: Bool)
    func setCommentsButton(selected: Bool)
    func setNavBarImage(image: String)
    func pushComments(comments: [String])
}

protocol DetailPresenterInterface: PresenterInterface {
    func powerstatsButtonTapped()
    func characteristicsButtonTapped()
    func commentsButtonTapped()
    func getFavorites()
    func favoritesButtonTapped()
    func commentPushButtonTapped(comment: String, date: Date)
    func getComments()
    func binButtonTapped()
}

protocol DetailInteractorInterface: InteractorInterface {
    func isInTheFavorites(entity: Heroes) -> Bool
    func delete(entity: Heroes, completion: BoolCompletition?)
    func insert(entity: Heroes, completion: BoolCompletition?)
    func insertComment(entity: Heroes, comment: String, date: Date, completion: BoolCompletition?)
    func deleteComment(entity: Heroes, completion: BoolCompletition?)
}
