//
//  DetailPresenter.swift
//  Superheroes
//
//  Created by Adam Cseke on 2022. 03. 03..
//  Copyright (c) 2022. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class DetailPresenter {

    // MARK: - Private properties -

    private unowned let view: DetailViewInterface
    private let interactor: DetailInteractorInterface
    private let wireframe: DetailWireframeInterface
    
    private var hero: Heroes

    // MARK: - Lifecycle -

    init(
        view: DetailViewInterface,
        interactor: DetailInteractorInterface,
        wireframe: DetailWireframeInterface,
        hero: Heroes
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
        self.hero = hero
    }
    
    func viewDidLoad() {
        view.pushHeroName(hero: hero)
    }
}

// MARK: - Extensions -

extension DetailPresenter: DetailPresenterInterface {
    func powerstatsButtonTapped() {
        view.setPowerstatsButton(selected: true)
    }
    
    func characteristicsButtonTapped() {
        view.setCharacteristicsButton(selected: true)
    }
    
    func commentsButtonTapped() {
        view.setCommentsButton(selected: true)
    }
    
}
