//
//  DetailWireframe.swift
//  Superheroes
//
//  Created by Adam Cseke on 2022. 03. 03..
//  Copyright (c) 2022. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class DetailWireframe: BaseWireframe {
    // MARK: - Module setup -

    init(hero: Heroes) {
        let moduleViewController = DetailViewController()
        moduleViewController.hidesBottomBarWhenPushed = true
        super.init(viewController: moduleViewController)
        
        let interactor = DetailInteractor()
        let presenter = DetailPresenter(view: moduleViewController, interactor: interactor, wireframe: self, hero: hero)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension DetailWireframe: DetailWireframeInterface {
    func presentAlert(title: String, description: String, buttonText: String, alertImage: UIImage, buttonTwoLabel: String, buttonTwoIsHidden: Bool, delegate: AlertViewDelegate?) {
        let alertVC = AlertViewController(title: title, message: description, buttonLabel: buttonText, alertImage: alertImage, buttonLabelTwo: buttonTwoLabel, buttonHidden: buttonTwoIsHidden)
        alertVC.modalTransitionStyle = .crossDissolve
        alertVC.modalPresentationStyle = .overFullScreen
        alertVC.alertDelegate = delegate
        navigationController?.present(alertVC, animated: true)
    }
}
